"""
bot/states.py — All conversation states as integer constants.
"""

(
    LANG_SELECT, MAIN_MENU,
    # Candidate
    C_RESUME_CHOICE, C_RESUME_UPLOAD, C_REVIEW_PARSED,
    C_NAME, C_GENDER, C_AGE, C_NATIONALITY, C_CITY,
    C_PHONE, C_LANGUAGES, C_EDUCATION, C_YEARS_EXP,
    C_INDUSTRY, C_POSITION, C_SALARY, C_LOCATIONS,
    C_AVAILABLE, C_EXTRAS, C_NOTES, C_REVIEW, C_CONFIRM,
    # Company
    B_COMPANY_NAME, B_INDUSTRY, B_ADDRESS, B_CONTACT_NAME,
    B_CONTACT_TITLE, B_PHONE, B_POSITION, B_HEADCOUNT,
    B_LOCATION, B_SALARY, B_HOURS, B_LANGUAGE, B_EXPERIENCE,
    B_BENEFITS, B_START_DATE, B_JD, B_SERVICE_FEE, B_UPLOAD, B_NOTES,
    B_REVIEW, B_CONFIRM,
    # Boss Show
    BS_COMPANY, BS_INDUSTRY, BS_CONTACT, BS_CONTACT_INFO,
    BS_TOPIC, BS_INTRO, BS_INTENT, BS_REVIEW, BS_CONFIRM,
) = range(53)

# Total step counts for progress display
CANDIDATE_TOTAL_STEPS = 16
COMPANY_TOTAL_STEPS = 17
BOSS_SHOW_TOTAL_STEPS = 7
